version: '3.8'

services:
  mdp-client:
    container_name: mdp-client
    restart: unless-stopped
    build:
      context: ./client
      dockerfile: docker/Dockerfile
    depends_on:
      - mdp-server
    networks:
      - internal-client
    environment:
      - NODE_ENV=production
      - REACT_APP_BASE_URL
    ports:
      - '3002:80'

  mdp-server:
    container_name: mdp-server
    restart: unless-stopped
    build:
      context: ./server
      dockerfile: docker/Dockerfile
    depends_on:
      - mdp-mongo
    environment:
      - NODE_ENV=production
      - MONGO_URI_PROD
      - GOOGLE_CLIENT_ID
      - GOOGLE_CLIENT_SECRET
      - GOOGLE_CALLBACK_URL
      - FACEBOOK_APP_ID
      - FACEBOOK_SECRET
      - FACEBOOK_CALLBACK_URL
      - JWT_SECRET_PROD
      - CLIENT_URL_PROD
      - SERVER_URL_PROD
    volumes:
      - ./server/public/images:/home/node/app/server/public/images
    networks:
      - default
      - internal-client
    ports:
      - '5001:80'

  mdp-mongo:
    image: mongo:6.0.3
    container_name: mdp-mongo
    restart: unless-stopped
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_DATABASE=mernboilerplate
    volumes:
      - ./server/docker/mongo-data:/data/db
    networks:
      - default

networks:
  default:
    name: mdp-default
  internal-client:
    name: mdp-client